/* eslint-disable @next/next/no-img-element */
import { updateProfileAction, removeCompanyLogoAction, uploadCompanyLogoAction } from "@/app/actions";
import { CompanySettingsForm } from "@/components/company-settings-form";
import { getCompanyLogoUrl, getCompanySettings } from "@/lib/company/settings";

export const instant = false;

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string; logo?: string }> }) {
  const data = await getCompanySettings();
  const params = await searchParams;
  if (!data.company) return <div className="summary-card text-sm text-slate-400">Não foi possível carregar os dados da empresa.</div>;
  const logoUrl = await getCompanyLogoUrl(data.company.logo_path);
  const message = params.error ? "Não foi possível salvar. Revise os dados e tente novamente." : params.logo === "updated" ? "Logo atualizada." : params.logo === "removed" ? "Logo removida." : params.saved ? "Dados salvos com sucesso." : null;
  return <div className="space-y-6"><div><p className="eyebrow">Administração</p><h1 className="mt-2 text-3xl font-semibold text-white">Configurações</h1><p className="mt-2 text-sm text-slate-400">Personalize a identidade da sua empresa prestadora.</p></div>{message && <p role={params.error ? "alert" : "status"} className={`rounded-lg border px-3 py-2 text-sm ${params.error ? "border-rose-400/30 bg-rose-400/10 text-rose-200" : "border-teal-300/30 bg-teal-300/10 text-teal-100"}`}>{message}</p>}<section className="summary-card space-y-5"><div><h2 className="text-xl font-semibold text-white">Empresa e contato</h2><p className="mt-1 text-sm text-slate-400">Esses dados aparecem nos documentos enviados aos clientes.</p></div><CompanySettingsForm company={data.company as Record<string, string | null | undefined>} /></section><section className="summary-card space-y-4"><div><h2 className="text-xl font-semibold text-white">Identidade visual</h2><p className="mt-1 text-sm text-slate-400">PNG, JPG ou WEBP até 5 MB. A logo fica isolada por empresa.</p></div>{logoUrl ? <img src={logoUrl} alt="Logo da empresa" className="h-24 max-w-full rounded-lg border border-white/10 bg-white object-contain p-3" /> : <div className="grid h-24 w-40 place-items-center rounded-lg border border-dashed border-teal-300/30 text-xs text-slate-500">Logo não cadastrada</div>}<form action={uploadCompanyLogoAction} encType="multipart/form-data" className="flex flex-wrap items-center gap-3"><input name="file" type="file" required accept="image/png,image/jpeg,image/webp" className="field-input max-w-full file:mr-3 file:rounded-md file:border-0 file:bg-teal-300 file:px-3 file:py-2 file:font-semibold file:text-slate-950" /><button className="button-primary">Enviar logo</button></form>{logoUrl && <form action={removeCompanyLogoAction}><button className="button-secondary">Remover logo</button></form>}</section><section className="summary-card space-y-4"><div><h2 className="text-xl font-semibold text-white">Meu perfil</h2><p className="mt-1 text-sm text-slate-400">Seu papel e permissões são controlados pela empresa.</p></div><form action={updateProfileAction} className="grid gap-4 sm:grid-cols-2"><label className="field-label">Nome completo<input name="fullName" required defaultValue={data.profile?.full_name ?? ""} className="field-input" /></label><label className="field-label">E-mail<input disabled value={data.user?.email ?? ""} readOnly className="field-input opacity-60" /></label><label className="field-label">Telefone opcional<input name="phone" type="tel" inputMode="tel" defaultValue={data.profile?.phone ?? ""} className="field-input" /></label><button className="button-primary sm:col-span-2">Salvar meu perfil</button></form></section></div>;
}
