import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { requireCompany } from "@/lib/auth/company";
import { createClient } from "@/lib/supabase/server";
import { createEquipmentModelAction } from "@/app/actions";

export const instant = false;

export default async function NewTechnicalModelPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const membership = await requireCompany();
  const params = await searchParams;
  const supabase = await createClient();
  const { data: manufacturers } = await supabase.from("manufacturers").select("id, name").eq("company_id", membership.company_id).order("name");
  const errorMessage = params.error ? "Não foi possível salvar o modelo. Revise os campos e tente novamente." : "";
  return <div className="mx-auto max-w-3xl"><Link href="/biblioteca-tecnica/modelos" className="mb-5 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" />Biblioteca técnica</Link><p className="eyebrow">Cadastro progressivo</p><h1 className="mt-2 text-3xl font-semibold text-white">Novo modelo técnico</h1><p className="mt-2 mb-8 text-sm text-slate-400">Comece pela identificação. Componentes, peças, especificações e documentos entram na ficha do modelo.</p>{errorMessage && <p role="alert" className="mb-5 rounded-lg border border-rose-300/30 bg-rose-300/10 px-4 py-3 text-sm text-rose-100">{errorMessage}</p>}<form action={createEquipmentModelAction} className="space-y-5"><section className="summary-card"><p className="eyebrow">1 · Identificação</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Fabricante<select required name="manufacturerId" className="select mt-2 w-full"><option value="">Selecione</option>{(manufacturers ?? []).map((manufacturer) => <option key={manufacturer.id} value={manufacturer.id}>{manufacturer.name}</option>)}</select></label><label className="text-sm text-slate-300">Categoria<select name="category" className="select mt-2 w-full"><option value="OTHER">Outro</option><option value="TREADMILL">Esteira</option><option value="CROSSOVER">Cross over</option><option value="BIKE">Bike</option><option value="ELLIPTICAL">Elíptico</option><option value="LEG_PRESS">Leg press</option><option value="LEG_EXTENSION">Cadeira extensora</option><option value="LEG_CURL">Mesa flexora</option><option value="CHEST_PRESS">Chest press</option><option value="FREE_WEIGHT">Peso livre</option></select></label><label className="text-sm text-slate-300">Nome do modelo<input required name="modelName" className="input mt-2" placeholder="Movement RT250" /></label><label className="text-sm text-slate-300">Código do modelo<input name="modelCode" className="input mt-2" placeholder="RT250" /></label></div></section><section className="summary-card"><p className="eyebrow">2 · Contexto técnico</p><label className="mt-4 block text-sm text-slate-300">Descrição<textarea name="description" rows={3} className="input mt-2" placeholder="Aplicação, características e identificação visual" /></label><label className="mt-4 block text-sm text-slate-300">Observações<textarea name="notes" rows={3} className="input mt-2" placeholder="Notas internas do prestador" /></label></section><div className="flex justify-end"><button className="button-primary" type="submit">Salvar e abrir ficha</button></div>{(!manufacturers || manufacturers.length === 0) && <p className="text-sm text-amber-200">Cadastre um fabricante antes de criar um modelo.</p>}</form></div>;
}
