import Link from "next/link";
import { FileText, Plus } from "lucide-react";
import { getQuotes } from "@/lib/quotes/queries";
import { formatQuoteCurrency } from "@/lib/quotes/calculations";
import type { QuoteStatus } from "@/types/database";

const labels: Record<string, string> = { DRAFT: "Rascunho", SENT: "Enviado", APPROVED: "Aprovado", REJECTED: "Recusado", EXPIRED: "Expirado", CONVERTED: "Convertido" };
export const instant = false;

export default async function QuotesPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const filter = (await searchParams).status;
  const quotes = await getQuotes(["DRAFT", "SENT", "APPROVED", "REJECTED", "EXPIRED", "CONVERTED"].includes(filter ?? "") ? filter as QuoteStatus : undefined);
  const filters = [["", "Todos"], ["DRAFT", "Rascunho"], ["SENT", "Enviado"], ["APPROVED", "Aprovado"], ["REJECTED", "Recusado"], ["EXPIRED", "Expirado"]];
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Financeiro operacional</p><h1 className="mt-2 text-3xl font-semibold text-white">Orçamentos</h1><p className="mt-2 text-sm text-slate-400">Propostas profissionais criadas a partir das visitas.</p></div><Link href="/orcamentos/novo" className="button-primary"><Plus className="h-4 w-4" />Novo orçamento</Link></div><div className="flex flex-wrap gap-2">{filters.map(([value, label]) => <Link key={label} href={value ? `/orcamentos?status=${value}` : "/orcamentos"} className={`rounded-full border px-3 py-1.5 text-xs ${filter === value || (!filter && !value) ? "border-teal-300/40 bg-teal-300/10 text-teal-100" : "border-white/10 text-slate-400"}`}>{label}</Link>)}</div><div className="summary-card overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Número</th><th className="px-4 py-3">Academia</th><th className="px-4 py-3">Data</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{quotes.map((quote) => <tr key={quote.id} className="border-b border-white/5 last:border-0"><td className="px-4 py-4"><Link href={`/orcamentos/${quote.id}`} className="font-semibold text-teal-200 hover:text-teal-100">{quote.quote_number}</Link></td><td className="px-4 py-4 text-slate-300">{quote.client?.name ?? "Academia"}</td><td className="px-4 py-4 text-slate-400">{new Date(quote.issued_at).toLocaleDateString("pt-BR")}</td><td className="px-4 py-4 text-white">{formatQuoteCurrency(Number(quote.total))}</td><td className="px-4 py-4"><span className="rounded-full border border-white/10 px-2 py-1 text-xs text-slate-300">{labels[quote.status] ?? quote.status}</span></td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{quotes.map((quote) => <Link key={quote.id} href={`/orcamentos/${quote.id}`} className="rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-teal-300" /><span className="font-semibold text-teal-200">{quote.quote_number}</span></div><span className="text-xs text-slate-400">{labels[quote.status] ?? quote.status}</span></div><p className="mt-3 text-sm text-white">{quote.client?.name ?? "Academia"}</p><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{new Date(quote.issued_at).toLocaleDateString("pt-BR")}</span><span className="text-slate-300">{formatQuoteCurrency(Number(quote.total))}</span></div></Link>)}{!quotes.length && <p className="py-8 text-center text-sm text-slate-500">Nenhum orçamento criado.</p>}</div></div></div>;
}
