import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseNfeXml, weightedAverageCost, MAX_NFE_XML_BYTES } from "@/lib/accounting/xml";
import { calendarStatus, calendarTotals } from "@/lib/accounting/calendar";

const validXml = `<NFe><infNFe Id="NFe35240112345678000199550010000000011000000018"><ide><nNF>1</nNF><serie>1</serie><dhEmi>2024-01-01T12:00:00-03:00</dhEmi></ide><emit><CNPJ>12345678000199</CNPJ><xNome>Fornecedor Teste</xNome></emit><dest><CNPJ>98765432000100</CNPJ></dest><det nItem="1"><prod><cProd>A1</cProd><xProd>Rolamento</xProd><NCM>84821010</NCM><CFOP>5102</CFOP><uCom>UN</uCom><qCom>2</qCom><vUnCom>10.00</vUnCom><vProd>20.00</vProd></prod></det><total><ICMSTot><vNF>20.00</vNF></ICMSTot></total></infNFe></NFe>`;
test("parser importa os campos essenciais da NF-e", () => { const parsed = parseNfeXml(validXml); assert.equal(parsed.accessKey.length, 44); assert.equal(parsed.supplierName, "Fornecedor Teste"); assert.equal(parsed.totalAmount, 20); assert.equal(parsed.items[0].quantity, 2); });
test("parser rejeita XXE e XML acima do limite", () => { assert.throws(() => parseNfeXml(`<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>${validXml}`)); assert.throws(() => parseNfeXml("x".repeat(MAX_NFE_XML_BYTES + 1))); });
test("custo médio ponderado combina estoques", () => { assert.equal(weightedAverageCost(10, 10, 10, 20), 15); });
test("migration cria unicidade por empresa para chave de acesso e políticas por company", () => { const sql = readFileSync("supabase/migrations/0012_accounting_inventory_core.sql", "utf8"); assert.match(sql, /unique \(company_id, access_key\)/i); assert.match(sql, /is_company_member\(company_id\)/i); assert.match(sql, /fiscal-documents/i); });
test("provider fiscal permanece explícito sem integração externa", () => { const source = readFileSync("src/lib/accounting/provider.ts", "utf8"); assert.match(source, /Emissão fiscal ainda não configurada/); });
test("entitlement PRO é guardado no servidor e migration mantém BASIC como padrão", () => { const migration = readFileSync("supabase/migrations/0013_pro_entitlements_hr_workspace.sql", "utf8"); const source = readFileSync("src/lib/access/entitlements.ts", "utf8"); assert.match(migration, /plan_code text not null default 'BASIC'/i); assert.match(migration, /has_company_feature/i); assert.match(source, /requireFeature/); assert.doesNotMatch(source, /NEXT_PUBLIC/); });
test("calendário classifica vencimentos e soma janelas reais", () => { const now = new Date("2026-10-07T12:00:00"); assert.equal(calendarStatus("2026-10-07", "UPCOMING", now), "DUE_TODAY"); assert.equal(calendarStatus("2026-10-01", "UPCOMING", now), "OVERDUE"); const totals = calendarTotals([{ due_date: "2026-10-10", amount: 100, status: "UPCOMING" }, { due_date: "2026-11-01", amount: 50, status: "UPCOMING" }, { due_date: "2026-10-01", amount: 20, status: "UPCOMING" }, { due_date: "2026-10-02", amount: 99, status: "PAID" }], now); assert.equal(totals.next7, 100); assert.equal(totals.next30, 150); assert.equal(totals.overdue, 20); });
test("migrations Dia 5 mantêm RLS e storage privado", () => { const calendar = readFileSync("supabase/migrations/0014_calendar_hr_payroll_extensions.sql", "utf8"); const portal = readFileSync("supabase/migrations/0016_accountant_portal_requests.sql", "utf8"); assert.match(calendar, /calendar_events[\s\S]*enable row level security/i); assert.match(calendar, /accounting-documents/); assert.match(portal, /accounting_client_links/); assert.match(portal, /document_requests/); });
