"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireFeature } from "@/lib/access/entitlements";
import { parseNfeXml } from "@/lib/accounting/xml";
import { getFiscalProvider } from "@/lib/accounting/provider";

const requireCompany = () => requireFeature("ACCOUNTING");

export async function importPurchaseInvoiceXmlAction(formData: FormData): Promise<void> {
  const membership = await requireCompany(); const file = formData.get("file");
  if (!(file instanceof File) || file.size === 0 || file.size > 10 * 1024 * 1024 || (!file.name.toLowerCase().endsWith(".xml") && file.type !== "application/xml" && file.type !== "text/xml")) redirect("/meu-contador/notas-recebidas?error=file");
  let parsed; try { parsed = parseNfeXml(await file.text()); } catch (error) { console.error("[accounting] XML import rejected", { companyId: membership.company_id, message: error instanceof Error ? error.message : "invalid_xml" }); redirect("/meu-contador/notas-recebidas?error=xml"); }
  const supabase = await createClient(); const supplierDocument = parsed.supplierDocument?.replace(/\D/g, "") || "";
  const existing = await supabase.from("suppliers").select("id").eq("company_id", membership.company_id).eq("document", supplierDocument).maybeSingle();
  let supplierId = existing.data?.id ?? null;
  if (!supplierId) { const created = await supabase.from("suppliers").insert({ company_id: membership.company_id, document: supplierDocument || "NÃO INFORMADO", legal_name: parsed.supplierName ?? "Fornecedor não identificado", active: true }).select("id").single(); if (created.error) { console.error("[accounting] supplier creation failed", { code: created.error.code, message: created.error.message, companyId: membership.company_id }); redirect("/meu-contador/notas-recebidas?error=supplier"); } supplierId = created.data.id; }
  const path = `${membership.company_id}/purchase-invoices/${crypto.randomUUID()}.xml`; const upload = await supabase.storage.from("fiscal-documents").upload(path, file, { contentType: "application/xml", upsert: false });
  if (upload.error) { console.error("[accounting] XML upload failed", { code: upload.error.name, message: upload.error.message, companyId: membership.company_id }); redirect("/meu-contador/notas-recebidas?error=upload"); }
  const result = await supabase.from("purchase_invoices").insert({ company_id: membership.company_id, supplier_id: supplierId, access_key: parsed.accessKey, number: parsed.number, series: parsed.series, issued_at: parsed.issueDate, supplier_document: parsed.supplierDocument, supplier_name: parsed.supplierName, recipient_document: parsed.recipientDocument, total_amount: parsed.totalAmount, status: "PENDING_REVIEW", xml_path: path, raw_metadata: parsed }).select("id").single();
  if (result.error || !result.data) { if (result.error?.code === "23505") redirect("/meu-contador/notas-recebidas?error=duplicate"); console.error("[accounting] purchase invoice creation failed", { code: result.error?.code, message: result.error?.message, companyId: membership.company_id }); await supabase.storage.from("fiscal-documents").remove([path]); redirect("/meu-contador/notas-recebidas?error=invoice"); }
  const items = parsed.items.map((item) => ({ company_id: membership.company_id, purchase_invoice_id: result.data.id, supplier_description: item.description, supplier_code: item.supplierCode, ncm: item.ncm, cfop: item.cfop, unit: item.unit, quantity: item.quantity, unit_cost: item.unitCost, total_cost: item.totalCost, taxes: item.taxes }));
  if (items.length) { const itemResult = await supabase.from("purchase_invoice_items").insert(items); if (itemResult.error) { console.error("[accounting] purchase invoice items failed", { code: itemResult.error.code, message: itemResult.error.message, invoiceId: result.data.id }); redirect("/meu-contador/notas-recebidas?error=items"); } }
  revalidatePath("/meu-contador"); revalidatePath("/meu-contador/notas-recebidas"); revalidatePath("/meu-contador/compras"); redirect("/meu-contador/notas-recebidas?imported=1");
}
export async function postPurchaseInvoiceAction(formData: FormData): Promise<void> { const invoiceId = String(formData.get("invoiceId") ?? ""); const membership = await requireCompany(); const supabase = await createClient(); const { error } = await supabase.rpc("post_purchase_invoice", { p_invoice_id: invoiceId }); if (error) { console.error("[accounting] post purchase failed", { code: error.code, message: error.message, invoiceId, companyId: membership.company_id }); redirect("/meu-contador/compras?error=post"); } revalidatePath("/meu-contador"); revalidatePath("/meu-contador/compras"); revalidatePath("/meu-contador/estoque"); redirect("/meu-contador/compras?posted=1"); }
export async function createSupplierAction(formData: FormData): Promise<void> { const membership = await requireCompany(); const name = String(formData.get("legalName") ?? "").trim(); if (name.length < 2) redirect("/meu-contador/fornecedores?error=validation"); const supabase = await createClient(); const { error } = await supabase.from("suppliers").insert({ company_id: membership.company_id, legal_name: name, trade_name: String(formData.get("tradeName") ?? "").trim() || null, document: String(formData.get("document") ?? "").replace(/\D/g, "") || "NÃO INFORMADO", email: String(formData.get("email") ?? "").trim() || null, phone: String(formData.get("phone") ?? "").replace(/\D/g, "") || null, active: true }); if (error) { console.error("[accounting] supplier failed", { code: error.code, message: error.message, companyId: membership.company_id }); redirect("/meu-contador/fornecedores?error=save"); } revalidatePath("/meu-contador"); revalidatePath("/meu-contador/fornecedores"); redirect("/meu-contador/fornecedores?saved=1"); }
export async function createInventoryProductAction(formData: FormData): Promise<void> { const membership = await requireCompany(); const name = String(formData.get("name") ?? "").trim(); if (name.length < 2) redirect("/meu-contador/estoque?error=validation"); const supabase = await createClient(); const { error } = await supabase.from("inventory_products").insert({ company_id: membership.company_id, name, sku: String(formData.get("sku") ?? "").trim() || null, unit: String(formData.get("unit") ?? "UNIDADE").trim(), minimum_stock: Number(formData.get("minimumStock") ?? 0) || 0, current_stock: 0, average_cost: 0, active: true }); if (error) { console.error("[accounting] inventory product failed", { code: error.code, message: error.message, companyId: membership.company_id }); redirect("/meu-contador/estoque?error=save"); } revalidatePath("/meu-contador"); revalidatePath("/meu-contador/estoque"); redirect("/meu-contador/estoque?saved=1"); }
export async function createObligationAction(formData: FormData): Promise<void> { const membership = await requireCompany(); const title = String(formData.get("title") ?? "").trim(); if (!title) redirect("/meu-contador/obrigacoes?error=validation"); const supabase = await createClient(); const { error } = await supabase.from("company_obligations").insert({ company_id: membership.company_id, title, type: String(formData.get("type") ?? "OUTRA"), reference_period: String(formData.get("period") ?? "NÃO INFORMADO"), due_date: String(formData.get("dueDate") ?? "") || null, status: "PENDING", source: "MANUAL" }); if (error) { console.error("[accounting] obligation failed", { code: error.code, message: error.message, companyId: membership.company_id }); redirect("/meu-contador/obrigacoes?error=save"); } revalidatePath("/meu-contador"); revalidatePath("/meu-contador/obrigacoes"); redirect("/meu-contador/obrigacoes?saved=1"); }
export async function saveFiscalSettingsAction(formData: FormData): Promise<void> { const membership = await requireCompany(); const supabase = await createClient(); const { error } = await supabase.from("fiscal_settings").upsert({ company_id: membership.company_id, provider_code: "MANUAL", fiscal_enabled: false, tax_regime: String(formData.get("taxRegime") ?? "").trim() || null }, { onConflict: "company_id" }); if (error) { console.error("[accounting] fiscal settings failed", { code: error.code, message: error.message, companyId: membership.company_id }); redirect("/meu-contador/configuracao-fiscal?error=save"); } revalidatePath("/meu-contador/configuracao-fiscal"); redirect("/meu-contador/configuracao-fiscal?saved=1"); }
export async function createManualFiscalInvoiceAction(formData: FormData): Promise<void> { await requireCompany(); try { await getFiscalProvider().issueServiceInvoice({ companyId: "manual", amount: Number(formData.get("amount") ?? 0), description: String(formData.get("description") ?? "") }); } catch (error) { console.error("[accounting] fiscal provider unavailable", { message: error instanceof Error ? error.message : "provider_error" }); redirect("/meu-contador/emitir-nota?error=not-configured"); } }
