import "server-only";
import { createClient } from "@/lib/supabase/server";
import { requireFeature } from "@/lib/access/entitlements";
const requireCompany = () => requireFeature("ACCOUNTING");
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function db(client: unknown) { return client as any; }
export async function getAccountingDashboard() { const membership = await requireCompany(); const supabase = await createClient(); const companyId = membership.company_id; const names = ["fiscal_invoices", "purchase_invoices", "inventory_products", "suppliers", "company_obligations"]; const counts = await Promise.all(names.map(async (name) => { const { count } = await db(supabase).from(name).select("id", { count: "exact", head: true }).eq("company_id", companyId); return [name, count ?? 0] as const; })); const map = Object.fromEntries(counts); const { count: lowStock } = await db(supabase).from("inventory_products").select("id", { count: "exact", head: true }).eq("company_id", companyId).filter("current_stock", "lte", "minimum_stock"); const { count: pending } = await db(supabase).from("purchase_invoices").select("id", { count: "exact", head: true }).eq("company_id", companyId).in("status", ["IMPORTED", "PENDING_REVIEW"]); return { issued: map.fiscal_invoices ?? 0, purchases: map.purchase_invoices ?? 0, stock: map.inventory_products ?? 0, suppliers: map.suppliers ?? 0, obligations: map.company_obligations ?? 0, lowStock: lowStock ?? 0, pending: pending ?? 0 }; }
async function list(table: string, columns: string, order = "created_at"): Promise<Record<string, unknown>[]> { const membership = await requireCompany(); const supabase = await createClient(); const { data, error } = await db(supabase).from(table).select(columns).eq("company_id", membership.company_id).order(order, { ascending: false }); if (error) { console.error("[accounting] query failed", { table, code: error.code, message: error.message, companyId: membership.company_id }); return []; } return (data ?? []) as Record<string, unknown>[]; }
export const getPurchaseInvoices = () => list("purchase_invoices", "id,access_key,number,series,issued_at,total_amount,status,supplier_id,created_at");
export const getSuppliers = () => list("suppliers", "id,legal_name,trade_name,document,email,phone,active");
export const getInventoryProducts = () => list("inventory_products", "id,sku,name,unit,current_stock,minimum_stock,average_cost,active");
export const getObligations = () => list("company_obligations", "id,title,type,reference_period,due_date,status,description");
export const getFiscalInvoices = () => list("fiscal_invoices", "id,number,status,provider_code,total_amount,issued_at,provider_message");
export async function searchFiscalInvoices(term = "") { const membership = await requireCompany(); const supabase = await createClient(); const query = db(supabase).from("fiscal_invoices").select("id,number,series,status,access_key,total_amount,issued_at,provider_code").eq("company_id", membership.company_id).order("created_at", { ascending: false }); const { data, error } = term ? await query.or(`number.ilike.%${term}%,series.ilike.%${term}%,access_key.ilike.%${term}%`) : await query; if (error) { console.error("[accounting] invoice search failed", { code: error.code, message: error.message, companyId: membership.company_id }); return []; } return (data ?? []) as Record<string, unknown>[]; }
export const getAccountingDocuments = () => list("accounting_documents", "id,category,name,document_date,storage_path,notes,created_at");
export async function getFiscalSettings() { const membership = await requireCompany(); const supabase = await createClient(); const { data } = await db(supabase).from("fiscal_settings").select("*").eq("company_id", membership.company_id).maybeSingle(); return data; }
export const getEmployees = () => list("employees", "id,full_name,document,job_title,hire_date,status,department");
export async function searchEmployees(term = "") { const membership = await requireCompany(); const supabase = await createClient(); const query = db(supabase).from("employees").select("id,full_name,document,job_title,hire_date,status,department").eq("company_id", membership.company_id).order("full_name", { ascending: true }); const { data } = term ? await query.or(`full_name.ilike.%${term}%,document.ilike.%${term}%,job_title.ilike.%${term}%`) : await query; return (data ?? []) as Record<string, unknown>[]; }
export async function getEmployeeDetail(id: string) { const membership = await requireCompany(); const supabase = await createClient(); const [{ data: employee }, { data: documents }, { data: vacations }, { data: leaves }] = await Promise.all([db(supabase).from("employees").select("*").eq("id", id).eq("company_id", membership.company_id).maybeSingle(), db(supabase).from("employee_documents").select("id,document_type,title,storage_path,document_date,notes,created_at").eq("employee_id", id).eq("company_id", membership.company_id).order("created_at", { ascending: false }), db(supabase).from("vacation_records").select("id,vacation_start,vacation_end,status,notes").eq("employee_id", id).eq("company_id", membership.company_id).order("vacation_start", { ascending: false }), db(supabase).from("employee_leaves").select("id,leave_type,start_date,end_date,status,notes").eq("employee_id", id).eq("company_id", membership.company_id).order("start_date", { ascending: false })]); return { employee: employee as Record<string, unknown> | null, documents: (documents ?? []) as Record<string, unknown>[], vacations: (vacations ?? []) as Record<string, unknown>[], leaves: (leaves ?? []) as Record<string, unknown>[] }; }
export const getVacations = () => list("employee_vacations", "id,employee_id,starts_on,ends_on,status,notes");
export const getVacationRecords = () => list("vacation_records", "id,employee_id,vacation_start,vacation_end,status,notes");
export const getGuides = () => list("payroll_guides", "id,guide_type,competence,due_date,amount,status,source");
export async function getCalendarEvents() { const membership = await requireCompany(); const supabase = await createClient(); const { data, error } = await db(supabase).from("calendar_events").select("id,title,description,category,due_date,amount,status,source_type,source_id,attachment_path,notes").eq("company_id", membership.company_id).order("due_date", { ascending: true }); if (error) { console.error("[accounting] calendar query failed", { code: error.code, message: error.message, companyId: membership.company_id }); return []; } return (data ?? []) as Record<string, unknown>[]; }
export async function getCalendarSummary() { await syncInAppAlerts(); const events = await getCalendarEvents(); const { calendarTotals } = await import("@/lib/accounting/calendar"); return { events, totals: calendarTotals(events.map((event) => ({ due_date: String(event.due_date), amount: Number(event.amount ?? 0), status: String(event.status) }))) }; }
export async function syncInAppAlerts() { const membership = await requireCompany(); const supabase = await createClient(); const { data: userData } = await supabase.auth.getUser(); const recipientId = userData.user?.id; if (!recipientId) return; const events = await getCalendarEvents(); const today = new Date(); for (const event of events) { if (["PAID", "COMPLETED", "CANCELLED"].includes(String(event.status))) continue; const due = new Date(`${String(event.due_date)}T00:00:00`); const base = new Date(today.getFullYear(), today.getMonth(), today.getDate()); const days = Math.ceil((due.getTime() - base.getTime()) / 86400000); const alert = [10, 5, 1, 0, -1].includes(days); if (!alert) continue; const title = days < 0 ? `Atrasado: ${String(event.title)}` : days === 0 ? `Vence hoje: ${String(event.title)}` : `${String(event.title)} vence em ${days} dia${days === 1 ? "" : "s"}`; const { error } = await db(supabase).from("in_app_notifications").upsert({ company_id: membership.company_id, recipient_id: recipientId, event_id: event.id, title, body: `Vencimento em ${String(event.due_date)}.`, created_at: new Date().toISOString() }, { onConflict: "event_id,title", ignoreDuplicates: true }); if (error) console.error("[accounting] alert sync failed", { code: error.code, message: error.message, eventId: event.id, companyId: membership.company_id }); } }
export async function getTodayTasks() { await syncInAppAlerts(); const events = await getCalendarEvents(); const { calendarStatus } = await import("@/lib/accounting/calendar"); const now = new Date(); return events.filter((event) => ["OVERDUE", "DUE_TODAY", "DUE_SOON", "WAITING_CONFIRMATION"].includes(calendarStatus(String(event.due_date), String(event.status), now))).slice(0, 20); }
export async function getAccountingOfficeLinks() { const membership = await requireFeature("ACCOUNTING_OFFICE"); const supabase = await createClient(); const { data, error } = await db(supabase).from("accounting_client_links").select("id,company_id,status,created_at").eq("accounting_firm_id", membership.company_id); if (error) { console.error("[accounting-office] links query failed", { code: error.code, message: error.message, companyId: membership.company_id }); return []; } return (data ?? []) as Record<string, unknown>[]; }
export async function getAccountingContacts() { const membership = await requireCompany(); const supabase = await createClient(); const { data, error } = await db(supabase).from("accounting_contacts").select("id,name,email,phone,firm_name,status,invited_at,created_at,accounting_contact_permissions(module_code,enabled)").eq("company_id", membership.company_id).order("created_at", { ascending: false }); if (error) { console.error("[accounting] contacts query failed", { code: error.code, message: error.message, companyId: membership.company_id }); return []; } return (data ?? []) as Record<string, unknown>[]; }
