import Link from "next/link";
import { ClipboardList, Plus } from "lucide-react";
import { getWorkOrders } from "@/lib/field-service/orders";

export const instant = false;

const labels: Record<string, string> = { DRAFT: "Rascunho", SCHEDULED: "Agendada", IN_PROGRESS: "Em andamento", WAITING_PARTS: "Aguardando peças", COMPLETED: "Concluída", CANCELLED: "Cancelada" };

export default async function WorkOrdersPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const filter = (await searchParams).status;
  const orders = await getWorkOrders(filter);
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Execução em campo</p><h1 className="mt-2 text-3xl font-semibold text-white">Ordens de serviço</h1><p className="mt-2 text-sm text-slate-400">Registre o que foi realmente executado, sem alterar o orçamento original.</p></div><Link href="/visitas/nova" className="button-primary"><Plus className="h-4 w-4" />Nova visita</Link></div><div className="flex flex-wrap gap-2">{[['', 'Todas'], ['SCHEDULED', 'Agendadas'], ['IN_PROGRESS', 'Em andamento'], ['WAITING_PARTS', 'Aguardando peças'], ['COMPLETED', 'Concluídas']].map(([value, label]) => <Link key={label} href={value ? `/ordens?status=${value}` : "/ordens"} className={`rounded-full border px-3 py-1.5 text-xs ${filter === value || (!filter && !value) ? "border-teal-300/40 bg-teal-300/10 text-teal-100" : "border-white/10 text-slate-400"}`}>{label}</Link>)}</div><section className="summary-card overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Ordem</th><th className="px-4 py-3">Academia</th><th className="px-4 py-3">Técnico</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Data</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b border-white/5 last:border-0"><td className="px-4 py-4"><Link href={`/ordens/${order.id}`} className="inline-flex items-center gap-2 font-semibold text-teal-200 hover:text-teal-100"><ClipboardList className="h-4 w-4" />{order.id.slice(0, 8).toUpperCase()}</Link></td><td className="px-4 py-4 text-slate-300">{order.clients?.name ?? "Academia"}</td><td className="px-4 py-4 text-slate-400">{order.profiles?.full_name ?? "Não atribuído"}</td><td className="px-4 py-4"><span className="rounded-full border border-white/10 px-2 py-1 text-xs text-slate-300">{labels[order.status] ?? order.status}</span></td><td className="px-4 py-4 text-slate-400">{new Date(order.created_at).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{orders.map((order) => <Link key={order.id} href={`/ordens/${order.id}`} className="rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between gap-3"><span className="font-semibold text-teal-200">OS {order.id.slice(0, 8).toUpperCase()}</span><span className="text-xs text-slate-400">{labels[order.status] ?? order.status}</span></div><p className="mt-3 text-sm text-white">{order.clients?.name ?? "Academia"}</p><p className="mt-1 text-xs text-slate-500">{order.profiles?.full_name ?? "Não atribuído"} · {new Date(order.created_at).toLocaleDateString("pt-BR")}</p></Link>)}{!orders.length && <p className="py-8 text-center text-sm text-slate-500">Nenhuma ordem de serviço encontrada.</p>}</div></section></div>;
}
